on: [push]

name: AzureBicepDeploy

jobs: 

        deploy:
            runs-on: ubuntu-latest
            steps:

                - name: Login to Azure
                  uses: azure/login@v2
                  with:
                    creds: ${{ secrets.AZURE_CREDENTIALS }}


                - name: Checkout Source code
                  uses: actions/checkout@v2

                
                - name: Deploy Bicep Template
                  uses: azure/cli@v2
                  with:
                    azcliversion: latest
                    inlineScript: |
                        az deployment group create \
                        --resource-group rg-storageaccount \
                        --template-file terraformtemplates/storageaccount.bicep
